### ISSUE TITLE
safari 浏览器问题反馈

### ISSUE THREAD

**Issue by ananasTete** [Byaidu/copymanga-helper#19]
- 环境：macos14.2、m1 芯片
- 脚本：Userscripts
- copymanag-helper 版本：10.9

问题

1. 点击“下一章”没反应。（上一章可以）
2. 鼠标移动到窗口左侧时，只有在顶部的空白页才会显示目录

**Comment by Byaidu** [comment]
建议换一下Violentmonkey或者Tampermonkey试试

**Comment by chenwynn** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
etouyang, @henrytirla, @theotow, @0xegobaby, @Kelvintbad, @MichaelFG, @beamthsa, @alexroan, @AkhileshManda, @samkenxstream, @GeorgeM140, @sternzhang, @shenqihui, @bobby7652, @no-decaf, @eleco, @amstalks, @doku01, @UnisniperV2, @KingLouisXVII
